from Domain.General import GEnergietraeger, GEnergietraegerKlasse, GEnergietraegerFactory


class GEnergietraegerDefaultFactory(GEnergietraegerFactory):
    def create(self, klassen: dict[str, GEnergietraegerKlasse]) -> dict[str, GEnergietraeger]:
        energietraeger_list = [GEnergietraeger('Braunkohle', klassen['Fossile fest']),
                               GEnergietraeger('Braunkohlen-Briketts', klassen['Fossile fest']),
                               GEnergietraeger('Brenntorf', klassen['Fossile fest']),
                               GEnergietraeger('Koks', klassen['Fossile fest']),
                               GEnergietraeger('Steinkohle', klassen['Fossile fest']),
                               GEnergietraeger('Benzin', klassen['Fossile flüssig']),
                               GEnergietraeger('Diesel', klassen['Fossile flüssig']),
                               GEnergietraeger('Heiz-Gasöl', klassen['Fossile flüssig']),
                               GEnergietraeger('Petroleum', klassen['Fossile flüssig']),
                               GEnergietraeger('Heizöl', klassen['Fossile flüssig']),
                               GEnergietraeger('Flüssiggas', klassen['Fossile flüssig']),
                               GEnergietraeger('Erdgas', klassen['Fossile gasförmig']),
                               GEnergietraeger('Mischgas', klassen['Fossile gasförmig']),
                               GEnergietraeger('Brennbare Abfälle', klassen['Brennbare Abfälle']),
                               GEnergietraeger('Scheitholz', klassen['Scheitholz']),
                               GEnergietraeger('Hausmüll Bioanteil', klassen['Biogene fest']),
                               GEnergietraeger('Pellets+Holzbriketts', klassen['Biogene fest']),
                               GEnergietraeger('Holzabfall', klassen['Biogene fest']),
                               GEnergietraeger('Holzkohle', klassen['Biogene fest']),
                               GEnergietraeger('Ablaugen', klassen['Biogene flüssig']),
                               GEnergietraeger('Deponiegas', klassen['Biogene gasförmig']),
                               GEnergietraeger('Klärgas', klassen['Biogene gasförmig']),
                               GEnergietraeger('Biogas', klassen['Biogene gasförmig']),
                               GEnergietraeger('Bioethanol', klassen['Biogene flüssig']),
                               GEnergietraeger('Biodiesel', klassen['Biogene flüssig']),
                               GEnergietraeger('Sonst. Biogene flüssig', klassen['Biogene flüssig']),
                               GEnergietraeger('Sonst. Biogene fest', klassen['Biogene fest']),
                               GEnergietraeger('Biogene', klassen['Biogene']),
                               GEnergietraeger('Geothermie', klassen['Erneuerbare Geothermie']),
                               GEnergietraeger('Umgebungswärme', klassen['Erneuerbare Umweltwärme']),
                               GEnergietraeger('Solarwärme', klassen['Erneuerbare Solarwärme']),
                               GEnergietraeger('Erneuerbare', klassen['Erneuerbare']),
                               GEnergietraeger('Fernwärme', klassen['Fernwärme']),
                               GEnergietraeger('Elektrische Energie', klassen['Elektrische Energie'])]
        return {energietraeger.name: energietraeger for energietraeger in energietraeger_list}
