from Domain.Energiebilanz import EBEnergietraeger, EBEnergietraegerFactory
from Domain.General import GData


class EBEnergietraegerDefaultFactory(EBEnergietraegerFactory):
    def create(self, g_data: GData) -> list[EBEnergietraeger]:
        return [EBEnergietraeger('Braunkohle', g_data.energietraeger['Braunkohle']),
                EBEnergietraeger('Braunkohlen-Briketts', g_data.energietraeger['Braunkohlen-Briketts']),
                EBEnergietraeger('Brenntorf', g_data.energietraeger['Brenntorf']),
                EBEnergietraeger('Koks', g_data.energietraeger['Koks']),
                EBEnergietraeger('Steinkohle', g_data.energietraeger['Steinkohle']),
                EBEnergietraeger('Benzin', g_data.energietraeger['Benzin']),
                EBEnergietraeger('Diesel', g_data.energietraeger['Diesel']),
                EBEnergietraeger('Gasöl für Heizzwecke', g_data.energietraeger['Heiz-Gasöl']),
                EBEnergietraeger('Petroleum', g_data.energietraeger['Petroleum']),
                EBEnergietraeger('Heizöl', g_data.energietraeger['Heizöl']),
                EBEnergietraeger('Flüssiggas', g_data.energietraeger['Flüssiggas']),
                EBEnergietraeger('Erdgas', g_data.energietraeger['Erdgas']),
                EBEnergietraeger('Mischgas', g_data.energietraeger['Mischgas']),
                EBEnergietraeger('Brennbare Abfälle', g_data.energietraeger['Brennbare Abfälle']),
                EBEnergietraeger('Scheitholz', g_data.energietraeger['Scheitholz']),
                EBEnergietraeger('Hausmüll Bioanteil', g_data.energietraeger['Hausmüll Bioanteil']),
                EBEnergietraeger('Pellets+Holzbriketts', g_data.energietraeger['Pellets+Holzbriketts']),
                EBEnergietraeger('Holzabfall', g_data.energietraeger['Holzabfall']),
                EBEnergietraeger('Holzkohle', g_data.energietraeger['Holzkohle']),
                EBEnergietraeger('Ablaugen', g_data.energietraeger['Ablaugen']),
                EBEnergietraeger('Deponiegas', g_data.energietraeger['Deponiegas']),
                EBEnergietraeger('Klärgas', g_data.energietraeger['Klärgas']),
                EBEnergietraeger('Biogas', g_data.energietraeger['Biogas']),
                EBEnergietraeger('Bioethanol', g_data.energietraeger['Bioethanol']),
                EBEnergietraeger('Biodiesel', g_data.energietraeger['Biodiesel']),
                EBEnergietraeger('Sonst. Biogene flüssig', g_data.energietraeger['Sonst. Biogene flüssig']),
                EBEnergietraeger('Sonst. Biogene fest', g_data.energietraeger['Sonst. Biogene fest']),
                EBEnergietraeger('Biogene Brenn- u. Treibstoffe', g_data.energietraeger['Biogene']),
                EBEnergietraeger('Geothermie', g_data.energietraeger['Geothermie']),
                EBEnergietraeger('Umgebungswärme', g_data.energietraeger['Umgebungswärme']),
                EBEnergietraeger('Solarwärme', g_data.energietraeger['Solarwärme']),
                EBEnergietraeger('Umgebungswärme etc.', g_data.energietraeger['Erneuerbare']),
                EBEnergietraeger('Fernwärme', g_data.energietraeger['Fernwärme']),
                EBEnergietraeger('Elektrische Energie', g_data.energietraeger['Elektrische Energie'])]
